### WINGS의 Integration Daily on the book by Hotel 활용

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from fbprophet import Prophet

In [2]:
data = pd.read_excel('data(2003.7_2022.02.21).xlsx')

In [3]:
#data[data['Date']=='2019-05-01'].index
#2019년 5월 1일 이후 최종예약률을 활용
data = data.loc[5783:,]

In [4]:
data.head()

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
5783,2019-05-01,Wed,92.0,0.0,80.0,87.0,"145,076","11,606,076","2,201,633",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
5784,2019-05-02,Thu,92.0,0.0,91.0,98.9,"154,487","14,058,310","1,806,407",59.0,...,0,"600,000",0,75.0,0.0,0.0,0.0,0,0,0
5785,2019-05-03,Fri,92.0,0.0,86.0,93.5,"169,271","14,557,265","1,764,634",59.0,...,"50,000","50,000",0,75.0,0.0,0.0,0.0,0,0,0
5786,2019-05-04,Sat,92.0,0.0,85.0,92.4,"176,205","14,977,387","1,438,771",58.0,...,"86,721","3,729,000",0,75.0,0.0,51.0,68.0,"103,928","5,300,305",0
5787,2019-05-05,Sun,91.0,0.0,86.0,94.5,"160,835","13,831,798","1,633,953",58.0,...,"86,047","3,700,000",0,75.0,0.0,52.0,69.3,"51,955","2,701,658",0

In [5]:
data.tail()

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
6806,2022-02-17,Thu,92.0,0.0,77.0,83.7,"181,530","13,977,772","1,927,629",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
6807,2022-02-18,Fri,92.0,0.0,82.0,89.1,"199,937","16,394,814","1,998,493",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
6808,2022-02-19,Sat,92.0,0.0,87.0,94.6,"195,250","16,986,738","1,602,173",59.0,...,"226,333","1,358,000",0,75.0,0.0,38.0,50.7,"52,565","1,997,470",0
6809,2022-02-20,Sun,92.0,0.0,81.0,88.0,"175,551","14,219,661","1,861,628",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
6810,2022-02-21,Mon,92.0,0.0,81.0,88.0,"184,183","14,918,846","1,612,766",59.0,...,"80,000","640,000",0,75.0,0.0,0.0,0.0,0,0,0

In [6]:
data['Date'] = pd.to_datetime(data['Date'])

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028 entries, 5783 to 6810
Data columns (total 51 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1028 non-null   datetime64[ns]
 1   Day        1028 non-null   object
 2   제주Ava      1028 non-null   float64
 3   제주H/U      1028 non-null   float64
 4   제주Sold     1028 non-null   float64
 5   제주Occ%     1028 non-null   float64
 6   제주ADR      1028 non-null   object
 7   제주Rm Rev.  1028 non-null   object
 8   제주FB Rev.  1028 non-null   object
 9   남원Ava      1028 non-null   float64
 10  남원H/U      1028 non-null   float64
 11  남원Sold     1028 non-null   float64
 12  남원Occ%     1028 non-null   float64
 13  남원ADR      1028 non-null   object
 14  남원Rm Rev.  1028 non-null   object
 15  남원FB Rev.  1028 non-null   object
 16  경주Ava      1028 non-null   float64
 17  경주H/U      1028 non-null   float64
 18  경주Sold     1028 non-null   float64
 19  경주Occ%     1028 non-null   float64
 20  경주ADR      1028 non-null   object
 21  경주Rm Rev.  1028 non-null   object
 22  경주FB Rev.  1028 non-null   object
 23  낙산Ava      977 non-null    float64
 24  낙산H/U      977 non-null    float64
 25  낙산Sold     977 non-null    float64
 26  낙산Occ%     977 non-null    float64
 27  낙산ADR      977 non-null    object
 28  낙산Rm Rev.  977 non-null    object
 29  낙산FB Rev.  977 non-null    object
 30  드림Ava      1028 non-null   float64
 31  드림H/U      1028 non-null   float64
 32  드림Sold     1028 non-null   float64
 33  드림Occ%     1028 non-null   float64
 34  드림ADR      1028 non-null   object
 35  드림Rm Rev.  1028 non-null   object
 36  드림FB Rev.  1028 non-null   object
 37  도고Ava      1028 non-null   float64
 38  도고H/U      1028 non-null   float64
 39  도고Sold     1028 non-null   float64
 40  도고Occ%     1028 non-null   float64
 41  도고ADR      1028 non-null   object
 42  도고Rm Rev.  1028 non-null   object
 43  도고FB Rev.  1028 non-null   object
 44  가평Ava      1028 non-null   float64
 45  가평H/U      1028 non-null   float64
 46  가평Sold     1028 non-null   float64
 47  가평Occ%     1028 non-null   float64
 48  가평ADR      1028 non-null   object
 49  가평Rm Rev.  1028 non-null   object
 50  가평FB Rev.  1028 non-null   object
dtypes: datetime64[ns](1), float64(28), object(22)
memory usage: 409.7+ KB

In [8]:
data.describe()

,제주Ava,제주H/U,제주Sold,제주Occ%,남원Ava,남원H/U,남원Sold,남원Occ%,경주Ava,경주H/U,...,드림Sold,드림Occ%,도고Ava,도고H/U,도고Sold,도고Occ%,가평Ava,가평H/U,가평Sold,가평Occ%
count,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,...,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000
mean,91.711089,0.254864,71.027237,80.808268,57.983463,0.511673,39.613813,68.181226,33.255837,0.105058,...,36.497082,37.391440,53.483463,0.516537,6.640078,12.655253,74.820039,0.179961,18.045720,24.115759
std,0.830993,0.731291,16.818674,17.101919,2.926347,2.014761,15.384703,26.038081,2.177095,0.782385,...,33.162475,33.971925,2.810593,2.810593,12.919526,24.541799,2.242744,2.242744,24.058045,32.124403
min,84.000000,0.000000,4.000000,6.400000,35.000000,0.000000,0.000000,0.000000,16.000000,0.000000,...,0.000000,0.000000,17.000000,0.000000,0.000000,0.000000,22.000000,0.000000,0.000000,0.000000
25%,92.000000,0.000000,62.000000,73.225000,58.000000,0.000000,27.000000,46.350000,34.000000,0.000000,...,1.000000,1.000000,54.000000,0.000000,0.000000,0.000000,75.000000,0.000000,0.000000,0.000000
50%,92.000000,0.000000,76.000000,87.000000,59.000000,0.000000,42.000000,71.300000,34.000000,0.000000,...,29.000000,29.000000,54.000000,0.000000,0.000000,0.000000,75.000000,0.000000,0.000000,0.000000
75%,92.000000,0.000000,84.000000,93.400000,59.000000,0.000000,54.000000,93.100000,34.000000,0.000000,...,64.000000,66.700000,54.000000,0.000000,5.000000,9.750000,75.000000,0.000000,35.000000,46.700000
max,92.000000,8.000000,92.000000,101.800000,59.000000,23.000000,59.000000,100.000000,34.000000,16.000000,...,100.000000,100.000000,54.000000,37.000000,54.000000,100.000000,75.000000,53.000000,75.000000,100.000000

In [9]:
df = data[['Date', '남원Occ%']]

In [10]:
df.columns = ['ds', 'y']

In [11]:
df

             ds      y
5783 2019-05-01   88.1
5784 2019-05-02   91.5
5785 2019-05-03   89.8
5786 2019-05-04  100.0
5787 2019-05-05  100.0
...         ...    ...
6806 2022-02-17   81.4
6807 2022-02-18   81.4
6808 2022-02-19  100.0
6809 2022-02-20   88.1
6810 2022-02-21   94.9

[1028 rows x 2 columns]

In [12]:
model = Prophet()

In [13]:
#model.add_country_holidays(country_name='KR')

In [14]:
model.fit(df)

INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
C:\Users\Owner\anaconda3\lib\site-packages\pystan\misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):

In [15]:
future = model.make_future_dataframe(periods=67, freq='1D')

In [16]:
pred = model.predict(future)

In [17]:
pred = pred[['ds','yhat','yhat_lower','yhat_upper']]
pred[['ds', 'yhat']].tail()

             ds        yhat
1090 2022-04-25   72.513029
1091 2022-04-26   72.303103
1092 2022-04-27   76.239927
1093 2022-04-28   92.149311
1094 2022-04-29  100.882536

In [18]:
pred.to_csv('남원Occ(2022.2.29~).csv')

In [19]:
# model.plot(pred)
# plt.show()

In [20]:
# model.plot_components(pred)
# plt.show()

In [21]:
# from fbprophet.plot import plot_plotly, plot_components_plotly
# plot_plotly(model, pred)

In [22]:
# plot_components_plotly(model, pred)